name: build
on: [push, pull_request]
jobs:
  meson:
    strategy:
      fail-fast: false
      matrix:
        image: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.image }}
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Meson
      run:  sudo -H pip3 install meson
    - name: Install system dependencies (Linux)
      if:   ${{ startsWith(matrix.image, 'ubuntu') }}
      run:  sudo apt-get install --no-install-recommends
            g++ libglfw3-dev libicu-dev libmpv-dev ninja-build
    - name: Install system dependencies (macOS)
      if:   ${{ startsWith(matrix.image, 'macos') }}
      run:  brew install glfw mpv ninja
    - name: Setup
      run:  meson setup build
    - name: Compile
      run:  ninja -C build
    - name: Test
      run:  meson test -C build
