name: build
on: [push, pull_request]
jobs:
  cmake:
    strategy:
      fail-fast: false
      matrix:
        image: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.image }}
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2
    - name: Install dependencies (Linux)
      if:   ${{ startsWith(matrix.image, 'ubuntu') }}
      run:  sudo apt-get install --no-install-recommends
            g++ libglfw3-dev libicu-dev libmpv-dev
    - name: Install dependencies (macOS)
      if:   ${{ startsWith(matrix.image, 'macos') }}
      run:  brew install boost glfw mpv
    - name: Configure
      run:  cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run:  cmake --build build
    - name: Verify
      run:  build/imagev --help
